
run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      username: juan-wills
      password: juan1234
      hostname: dagster-metadata-postgres
      port: 5432
      db_name: dagster-metadata


schedule_storage:
  module: dagster_postgres.schedule_storage
  class: PostgresScheduleStorage
  config:
    postgres_db:
      username: juan-wills
      password: juan1234
      hostname: dagster-metadata-postgres
      port: 5432
      db_name: dagster-metadata


event_log_storage:
  module: dagster_postgres.event_log
  class: PostgresEventLogStorage
  config:
    postgres_db:
      username: juan-wills
      password: juan1234
      hostname: dagster-metadata-postgres
      port: 5432
      db_name: dagster-metadata

compute_logs:
  module: dagster.core.storage.local_compute_log_manager
  class: LocalComputeLogManager
  config:
    base_dir: ${DAGSTER_HOME}/compute_logs
telemetry:
  enabled: false